# Solution 3.1
1.
SELECT UPPER(SUBSTR(COUNTRY_NAME, 1,3)) "FIRST 3 CHARS" ,UPPER(SUBSTR(COUNTRY_NAME, LENGTH(COUNTRY_NAME)-3+1)) "LAST 3 CHARS" 
FROM COUNTRIES;

2.
SELECT LPAD((FIRST_NAME||' '||LAST_NAME),60,'* ' ) "FULL NAME" 
FROM EMPLOYEES ;

3.
SELECT JOB_TITLE
FROM JOBS 
WHERE LOWER(JOB_TITLE) LIKE '%manager%'; 
