# Solution 3.2
1.
SELECT LAST_NAME,ROUND(SYSDATE-HIRE_DATE,2) "NUMBER OF DAYS EMPLOYEED" 
FROM EMPLOYEES;

2.
SELECT LAST_NAME,ROUND((SYSDATE-HIRE_DATE)/365,2) "NUMBER OF YEARS EMPLOYEED" 
FROM EMPLOYEES;

