# Solution 3.4

1.
SELECT FIRST_NAME,COMMISSION_PCT
FROM EMPLOYEES
WHERE NVL(COMMISSION_PCT,0)>=.2;

2.
SELECT LAST_NAME,(SALARY*65 + SALARY*65*NVL(COMMISSION_PCT, 0) ) "TOTAL_SALARY" 
FROM EMPLOYEES 
WHERE NVL(COMMISSION_PCT, -1) = -1 ;

