# Solution 4.1
1.
SELECT MANAGER_ID, COUNT(* ) "NUMBER OF EMPLOYEES"
FROM EMPLOYEES
GROUP BY MANAGER_ID;

2.
SELECT DEPARTMENT_ID, COUNT(* ) "NUMBER OF EMPLOYEES" 
FROM EMPLOYEES
WHERE SALARY>=3000
GROUP BY DEPARTMENT_ID;

3.
SELECT DEPARTMENT_ID,MIN(SALARY) "MINIMUM SALARY" , MAX(SALARY) "MAXIMUM SALARY" ,ROUND(AVG(SALARY),3) "AVARAGE SALARY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID<>80
GROUP BY DEPARTMENT_ID
ORDER BY AVG(SALARY) DESC, MAX(SALARY)  DESC,MIN(SALARY) DESC ;

