# Solution 4.3

1.
SELECT  TRUNC(SALARY/5000,0)  "GROUPR NUMBER",  COUNT(* ) 
FROM EMPLOYEES 
GROUP BY TRUNC(SALARY/5000,0) 
ORDER BY TRUNC(SALARY/5000,0)  ASC;

2.
SELECT  JOB_ID,TO_CHAR(HIRE_DATE,'YYYY') YEAR,  COUNT(* ) TOTAL 
FROM EMPLOYEES
GROUP BY JOB_ID,TO_CHAR(HIRE_DATE,'YYYY'
ORDER BY TO_CHAR(HIRE_DATE,'YYYY'),JOB_ID ;
