1.
SELECT C.COUNTRY_ID,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID  RIGHT OUTER JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
GROUP BY C.COUNTRY_ID;

2.
SELECT C.COUNTRY_ID,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID  JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
GROUP BY C.COUNTRY_ID
UNION
SELECT C.COUNTRY_ID,0
FROM COUNTRIES C
WHERE C.COUNTRY_ID not  in(
SELECT C.COUNTRY_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID  JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
)
;
3.
SELECT E.LAST_NAME,E.JOB_ID,E.SALARY,J.AVGSAL,J.CO
FROM EMPLOYEES E,(SELECT JOB_ID,AVG(SALARY) AVGSAL,COUNT(*) CO FROM EMPLOYEES E GROUP BY JOB_ID) J
WHERE E.JOB_ID=J.JOB_ID AND E.SALARY BETWEEN (J.AVGSAL-1000) AND (J.AVGSAL+1000);

4.
SELECT e.last_name
from employees e
where 3<=(SELECT count(*)
from employees e2
where e2.salary<e.salary and e.DEPARTMENT_ID=e2.department_id)
;
