# Solution 5.1
1.
SELECT LAST_NAME,SALARY, JOB_TITLE
FROM EMPLOYEES e JOIN JOBS j 
on (e.JOB_ID=j.JOB_ID);
2.
SELECT DEPARTMENT_NAME, COUNTRY_NAME
FROM DEPARTMENTS d join
LOCATIONS l
on (d.LOCATION_ID=l.LOCATION_ID)
join COUNTRIES c on( l.COUNTRY_ID=c.COUNTRY_ID);
3.
SELECT  c.COUNTRY_NAME,COUNT(* ) "NUMBER OF DEPARTMENTS"
FROM DEPARTMENTS d join
LOCATIONS l
on (d.LOCATION_ID=l.LOCATION_ID)
join COUNTRIES c on( l.COUNTRY_ID=c.COUNTRY_ID)
GROUP BY c.COUNTRY_ID,c.COUNTRY_NAME;
4.
SELECT j.JOB_ID ,COUNT(* ) 
FROM EMPLOYEES e  
join  JOB_HISTORY j on(e.JOB_ID=j.JOB_ID)  
GROUP BY j.JOB_ID;  
5.
SELECT d.DEPARTMENT_NAME,j.JOB_TITLE,COUNT(* ) "WORKING EMPLOYEES" 
FROM DEPARTMENTS d
join EMPLOYEES e on (e.department_id=d.DEPARTMENT_ID)
join JOBS j on (e.JOB_ID=j.JOB_ID)
GROUP BY d.DEPARTMENT_NAME,j.JOB_TITLE
ORDER BY d.DEPARTMENT_NAME;
6.
SELECT E1.LAST_NAME, COUNT(* ) TOTAL 
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 
ON (E1.HIRE_DATE < E2.HIRE_DATE) 
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME 
ORDER BY E1.LAST_NAME ASC ; 
7.
SELECT E1.LAST_NAME, COUNT(*) "JOINED BEFORE", ( SELECT COUNT(*) FROM EMPLOYEES )-COUNT(*) "JOINED AFTER" 
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON(TO_DATE(E1.HIRE_DATE) > TO_DATE(E2.HIRE_DATE))
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME;
8.
SELECT E1.LAST_NAME, COUNT(* ) HIGHSAL
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.SALARY < E2.SALARY)
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
HAVING COUNT(* ) >3
ORDER BY E1.LAST_NAME ASC ;
9.
SELECT E1.LAST_NAME, COUNT(* ) RANK 
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.SALARY < E2.SALARY)
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
ORDER BY  COUNT(* ) ASC ;
10.
SELECT E1.LAST_NAME, COUNT(* ) RANK
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.SALARY < E2.SALARY)
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
HAVING COUNT(* )<=3;

