--solution 6.1

1. Select last_name
FROM EMPLOYEES
WHERE DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Sales');
2. Select last_name,salary
FROM EMPLOYEES
WHERE SALARY> ANY ( select salary from employees where department_id=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Sales'));
3. Select last_name,salary
FROM EMPLOYEES
WHERE SALARY> ALL ( select salary from employees where department_id=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Sales'));
4. Select last_name,salary
FROM EMPLOYEES
WHERE SALARY
BETWEEN ( SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Sales'))-5000
and ( SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Sales'))+5000;
