--solution 6.2
a. SELECT Last_name,salary
FROM EMPLOYEES E1
WHERE 3 <= (
SELECT COUNT(*)
FROM EMPLOYEES E2
WHERE E2.SALARY < E1.SALARY
) ;
b.
SELECT d.DEPARTMENT_NAME,avg(salary)
FROM DEPARTMENTS d,EMPLOYEES e
WHERE d.DEPARTMENT_ID=e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID,d.DEPARTMENT_NAME
HAVING avg(salary)> all (SELECT min(salary)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID)
;
c. SELECT d.DEPARTMENT_NAME,COUNT(*)
FROM DEPARTMENTS d,EMPLOYEES e
WHERE d.DEPARTMENT_ID=e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID,d.DEPARTMENT_NAME
HAVING COUNT(*)= (SELECT max(COUNT(*))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID)
;
d. SELECT e.LAST_NAME, count(d.department_id)
FROM Employees e, Departments d
where e.department_id=d.department_id
GROUP BY e.LAST_NAME
HAVING COUNT(e.department_id)>=2;

e. SELECT E1.LAST_NAME, E1.SALARY, MIN(E2.SALARY), MAX(E2.SALARY)
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.DEPARTMENT_ID = E2.DEPARTMENT_ID)
GROUP BY E1.DEPARTMENT_ID, E1.LAST_NAME, E1.SALARY
ORDER BY E1.SALARY ;
f. select LAST_NAME,j.JOB_TITLE
from EMPLOYEES e join JOBS j on e.JOB_ID=j.JOB_ID
 join (select JOB_ID, max(salary) ms from employees group by JOB_ID) m
  on e.JOB_ID = m.JOB_ID and e.salary = m.ms;
