-- solution 11.2
1. DECLARE
YEARS NUMBER ;
COUNTER NUMBER ;
OLD_SAL NUMBER;
NEW_SAL NUMBER;
BEGIN
FOR R IN (SELECT FIRST_NAME, EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES )
LOOP
IF to_char(R.HIRE_DATE, 'MM-DD') = to_char(sysdate, 'MM-DD') THEN
DBMS_OUTPUT.PUT_LINE('HAPPY ANNIVERSARY ' ||  R.FIRST_NAME);
END IF;
END LOOP ;
END ;
/
