# Solution 2.1
1. SELECT COUNTRY_NAME
FROM COUNTRIES;

2. SELECT JOB_TITLE 
FROM JOBS;

3.
SELECT MANAGER_ID<br>
FROM EMPLOYEES;

4.
SELECT LOCATION_ID, ( STREET_ADDRESS || ',' || CITY || ',' || STATE_PROVINCE || ',' || POSTAL_CODE ) ADDRESS
FROM LOCATIONS;

