# Solution 2.2
1.
SELECT (FIRST_NAME ||' ' || LAST_NAME) Name, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE< ('01-JAN-1998');

2.
SELECT * 
FROM LOCATIONS 
WHERE COUNTRY_ID IN (
(SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME='Canada'),
(SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME ='Germany'),
(SELECT COUNTRY_ID FROM COUNTRIES WHERE c COUNTRY_NAME ='United Kingdom')
);

3.
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

4.
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'a%';

5.
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 's%n';

6.
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE MANAGER_ID=100;


7. SELECT LAST_NAME
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES' AND SALARY>=23000;


8.
SELECT * 
FROM EMPLOYEES
WHERE LAST_NAME NOT LIKE '%s%';


9.
SELECT (FIRST_NAME ||' ' || LAST_NAME) Name, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT<=.30;

10.
SELECT (FIRST_NAME ||' ' || LAST_NAME) Name, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE>= ('01-JAN-1998');

11.
SELECT (FIRST_NAME ||' ' || LAST_NAME) Name, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-1998' AND '31-DEC-1998';


