# SOLUTION 2.3

1.
SELECT (FIRST_NAME ||' ' || LAST_NAME) Name, SALARY,COMMISSION_PCT
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES'
ORDER BY COMMISSION_PCT ASC,SALARY DESC;

2.
SELECT COUNTRY_NAME
FROM COUNTRIES
ORDER BY COUNTRY_NAME ASC;

