-- practicr sql 1
1. select * FROM employee
where empmsal<1000;

2. SELECT DISTINCT DEPTNO FROM EMPLOYEE;

3. SELECT *
FROM EMPLOYEE
WHERE DEPTNO=20 AND EMPMSAL<2500;

4. SELECT *
FROM EMPLOYEE
WHERE EMPMSAL>EMPCOMM AND EMPCOMM IS NOT NULL;

5. SELECT *
FROM EMPLOYEE
WHERE EMPJOB LIKE '%R';

6. SELECT *
FROM EMPLOYEE
WHERE EMPNAME  LIKE 'J%' OR EMPNAME LIKE 'K%' OR EMPNAME LIKE 'M%';

7. SELECT *
FROM EMPLOYEE
WHERE EMPMSAL>1500 AND EMPBDATE<TO_DATE('01-JAN-60');

8.  SELECT *
FROM EMPLOYEE
WHERE EMPCOMM IS NOT NULL;

9. SELECT *
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO FROM DEPARTMENT WHERE DEPTLOCATION='NEW YORK');

10. SELECT *
FROM EMPLOYEE
WHERE DEPTNO=any (SELECT DEPTNO FROM DEPARTMENT WHERE DEPTLOCATION !='NEW YORK' AND DEPTLOCATION !='CHICAGO');

11. SELECT *
FROM EMPLOYEE
WHERE EMPBDATE BETWEEN TO_DATE('01-JAN-60') AND TO_DATE('31-DEC-65')
ORDER BY EMPBDATE;

12.  SELECT *
FROM EMPLOYEE
WHERE EMPMSAL<1500 OR EMPMSAL>3000 ;

13.  SELECT *
FROM EMPLOYEE
WHERE MGRNO IS NOT NULL ;

14. SELECT *
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO FROM DEPARTMENT WHERE DEPTLOCATION='DALLAS') OR EMPNO=any(SELECT MGRNO FROM EMPLOYEE) OR EMPMSAL>2500;

15. SELECT EMPNAME "NAME",EMPJOB "JOB", EMPMSAL "SALARY"
FROM EMPLOYEE
ORDER BY SALARY;

16.SELECT DEPTNAME,DEPTLOCATION,EMPNAME
FROM EMPLOYEE e,DEPARTMENT d
WHERE e.DEPTNO=d.DEPTNO
ORDER BY DEPTNAME;

17. SELECT EMPNAME,EMPJOB,(SELECT d.EMPNAME FROM EMPLOYEE d WHERE e.MGRNO=d.EMPNO) "MANAGER NAME"
FROM EMPLOYEE e
ORDER BY (SELECT d.EMPNAME FROM EMPLOYEE d WHERE e.MGRNO=d.EMPNO);

18. SELECT EMPNAME,DEPTNAME,HISTBEGINDATE,HISTENDDATE,HISTMSAL
FROM EMPLOYEE E,HISTORY H,DEPARTMENT D
WHERE E.EMPNO=H.EMPNO AND H.DEPTNO=D.DEPTNO
ORDER BY EMPNAME, H.HISTBEGINDATE DESC;

19. SELECT EMPNAME,EMPJOB,EMPMSAL,EMPMSAL*12 ANNUALSALARY
FROM EMPLOYEE;

20. SELECT EMPNAME,EMPJOB,EMPMSAL,EMPCOMM,EMPMSAL*12+NVL(EMPCOMM,0)*EMPMSAL*12 ANNUALSALARY
FROM EMPLOYEE;
