-- practicr sql 2
1. SELECT EMPNAME,EMPMSAL*12 ANSALURY, EMPMSAL*12+(EMPMSAL*12*.1) "ANNUAL  NEW SALARY"
FROM EMPLOYEE;

2. SELECT EMPNAME,ROUND((SYSDATE-EMPBDATE),2)"AGE"
FROM EMPLOYEE;

3.  SELECT EMPNAME,EMPJOB,EMPMSAL,EMPMSAL*12 ANNUALSALARY
FROM EMPLOYEE;

4. SELECT ('EMPLOYEE ' || EMPNAME ||'IS A ' || EMPJOB || 'AND WORKS IN ' || (SELECT DEPTNAME FROM DEPARTMENT D WHERE D.DEPTNO=E.DEPTNO))
FROM EMPLOYEE E;


5.SELECT EMPNAME,EMPBDATE,ROUND((SYSDATE-EMPBDATE)*12,2) "AGE"
FROM EMPLOYEE;

6. SELECT EMPNAME
FROM EMPLOYEE
WHERE (TO_CHAR(EMPBDATE,'MON'))='FEB';

7. SELECT EMPNAME
FROM EMPLOYEE
WHERE EMPCOMM=GREATEST(EMPMSAL,EMPCOMM);

8. SELECT ('EMPLOYEE ' || EMPNAME ||'WAS BORN ON ' || to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'DAY') || 'THE ' || to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'dd') ||'of '||
to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'mm')||',19'||to_char(to_date(EMPBDATE,'dd/mm/yy'), 'yy'))
FROM EMPLOYEE E;

9.SELECT E.EMPNAME,COUNT(*)
FROM EMPLOYEE E,REGISTRATION R
WHERE E.EMPNO=R.EMPNO
GROUP BY R.EMPNO,E.EMPNAME;

10. SELECT *
FROM EMPLOYEE
WHERE EMPBDATE=ANY (SELECT MAX(EMPBDATE) FROM EMPLOYEE );

11. SELECT DEPTNO,(SELECT DEPTNAME FROM DEPARTMENT D WHERE D.DEPTNO=E.DEPTNO) DEPTNAME,COUNT(*) NbrOfEmployees,
MAX(EMPMSAL) MaxSalary,MIN(EMPMSAL) Minsalary,ROUND(AVG(EMPMSAL),2) AVGSALARY,ROUND(AVG(EMPMSAL)*COUNT(*),0) TOTALSALARY
FROM EMPLOYEE E
GROUP BY DEPTNO;

12. SELECT DEPTNO,(SELECT DEPTNAME FROM DEPARTMENT D WHERE D.DEPTNO=E.DEPTNO) DEPTNAME,EMPJOB,EMPMSAL
FROM EMPLOYEE E;

13. SELECT EMPNAME
FROM EMPLOYEE E
WHERE E.EMPMSAL>(SELECT AVG(EMPMSAL) FROM EMPLOYEE D  );

14. SELECT DEPTNO
FROM EMPLOYEE E
GROUP BY DEPTNO
HAVING AVG(EMPMSAL)=ANY( SELECT MAX(AVG(EMPMSAL)) FROM EMPLOYEE D GROUP BY DEPTNO);

15. SELECT CRSCODE
FROM OFFERING E
GROUP BY CRSCODE
HAVING COUNT(EMPNO)=ANY( SELECT MAX(COUNT(EMPNO)) FROM OFFERING D GROUP BY CRSCODE);

17. SELECT EMPNO
FROM EMPLOYEE
MINUS
SELECT EMPNO
FROM REGISTRATION;

18. SELECT EMPNO
FROM REGISTRATION
INTERSECT
SELECT EMPNO
FROM OFFERING;

19. INSERT INTO EMPLOYEE
VALUES(9999,'Bear','HB','MILLER',TO_DATE('21-JUL-1965'),3500,NULL,10,NULL);

20. UPDATE EMPLOYEE

SET EMPMSAL=(SELECT EMPMSAL FROM EMPLOYEE WHERE EMPNAME='KING'),
EMPJOB='CLARK' ,
DEPTNO=(SELECT DEPTNO FROM DEPARTMENT WHERE DEPTNAME='SALES')

WHERE EMPNAME='Bear';

21. DELETE FROM EMPLOYEE
WHERE EMPNAME='Bear';
