-- practicr sql 2
1. SELECT EMPNAME,EMPMSAL*12 ANSALURY, EMPMSAL*12+(EMPMSAL*12*.1) "ANNUAL  NEW SALARY"
FROM EMPLOYEE;

2. SELECT EMPNAME,ROUND((SYSDATE-EMPBDATE),2)"AGE"
FROM EMPLOYEE;

3.  SELECT EMPNAME,EMPJOB,EMPMSAL,EMPMSAL*12 ANNUALSALARY
FROM EMPLOYEE;

4. SELECT ('EMPLOYEE ' || EMPNAME ||'IS A ' || EMPJOB || 'AND WORKS IN ' || (SELECT DEPTNAME FROM DEPARTMENT D WHERE D.DEPTNO=E.DEPTNO))
FROM EMPLOYEE E;


5.SELECT EMPNAME,EMPBDATE,ROUND((SYSDATE-EMPBDATE)*12,2) "AGE"
FROM EMPLOYEE;

6. SELECT EMPNAME
FROM EMPLOYEE
WHERE (TO_CHAR(EMPBDATE,'MON'))='FEB';

7. SELECT EMPNAME
FROM EMPLOYEE
WHERE EMPCOMM=GREATEST(EMPMSAL,EMPCOMM);

8. SELECT ('EMPLOYEE ' || EMPNAME ||'WAS BORN ON ' || to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'DAY') || 'THE ' || to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'dd') ||'of '||
to_char(to_date(EMPBDATE,'dd/mm/yyyy'), 'mm')||',19'||to_char(to_date(EMPBDATE,'dd/mm/yy'), 'yy'))
FROM EMPLOYEE E;

9.SELECT E.EMPNAME,COUNT(*)
FROM EMPLOYEE E,REGISTRATION R
WHERE E.EMPNO=R.EMPNO
GROUP BY R.EMPNO,E.EMPNAME;

10. SELECT *
FROM EMPLOYEE
WHERE EMPBDATE=ANY (SELECT MAX(EMPBDATE) FROM EMPLOYEE );

11.
