
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (1,'Nonummy LLP',16);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (2,'Ligula Associates',1);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (3,'Aliquet Proin Velit LLC',72);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (4,'Odio LLC',42);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (5,'Metus Facilisis Institute',41);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (6,'Proin Non Corp.',74);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (7,'Diam Nunc Company',46);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (8,'Diam Foundation',45);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (9,'Enim Etiam Industries',67);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (10,'Auctor Associates',26);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (11,'Eu Corp.',48);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (12,'Fring Consulting',95);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (13,'Vestibulum Massa Company',13);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (14,'Dui PC',55);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (15,'Magna Sed Eu Institute',84);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (16,'Enim Industries',29);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (17,'Turpis Nec LLC',3);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (18,'Est Vitae Company',3);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (19,'Nec Mauris Blandit LLP',30);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (20,'Quis Inc.',42);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (21,'Imperdiet Industries',83);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (22,'Quam Curabitur Industries',11);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (23,'Faucibus Leo In LLC',53);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (24,'Orci Tincidunt Company',31);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (25,'Integer Vitae Nibh Company',23);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (26,'Mattis Semper Inc.',8);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (27,'Non Enim Industries',3);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (28,'Vitae Purus Gravida Corp.',52);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (29,'Mus Incorporated',40);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (30,'Senectus Et Netus Ltd',95);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (31,'Semper Limited',92);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (32,'Nulla LLC',14);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (33,'Consectetuer Consulting',66);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (34,'Eu Sem Company',1);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (35,'Semper Tellus Corp.',100);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (36,'Et Corp.',18);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (37,'Velit Industries',88);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (38,'Nibh Ltd',33);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (39,'Scelerisque Associates',48);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (40,'Pede Blandit Incorporated',26);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (41,'Metus Eu Erat Ltd',92);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (42,'Eu Tellus Eu Corp.',38);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (43,'Amet Lorem Semper Foundation',94);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (44,'Ut Nec Industries',49);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (45,'Purus Industries',85);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (46,'Orci Ut Company',41);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (47,'Scelerisque Corporation',4);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (48,'Turpis Company',59);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (49,'Erat Incorporated',96);
INSERT INTO Publisher (Publisher_id,Publisher_name,Location_id) VALUES (50,'Massa LLC',21);

