INSERT INTO Branch (Branch_id,Branch_name) VALUES (1,'Germany');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (2,'Belgium');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (3,'Malaysia');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (4,'Russian Federation');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (5,'French');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (6,'Antarctica');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (7,'Cameroon');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (8,'South Africa');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (9,'United Arab Emirates');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (10,'Ireland');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (11,'Albania');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (12,'Tokelau');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (13,'Finland');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (14,'Iraq');
INSERT INTO Branch (Branch_id,Branch_name) VALUES (15,'United Kingdom (Great Britain)');
