1.
create or replace FUNCTION GET_AUTHOR_NAME(EID IN VARCHAR2)
RETURN VARCHAR2 IS
MSG VARCHAR2(100) ;
COUNTER NUMBER;
BEGIN
MSG:='';
COUNTER:=0;
FOR R IN (Select AUTHOR_NAME from AUTHOR WHERE BOOK_ID=EID)
LOOP
COUNTER:=COUNTER+1;
IF COUNTER>1 THEN
MSG:=MSG||',';
END IF;
MSG:=MSG||R.AUTHOR_NAME;
END LOOP ;
RETURN MSG ;
END;
