--solution 8.2
a. UPDATE EMPLOYEES
SET COMMISSION_PCT=NULL
WHERE COMMISSION_PCT =0;
b. UPDATE EMPLOYEES
SET SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);
c. UPDATE EMPLOYEES e
SET e.COMMISSION_PCT=e.COMMISSION_PCT*   (SELECT COUNT(*) FROM EMPLOYEES s WHERE s.MANAGER_ID=e.EMPLOYEE_ID GROUP BY e.MANAGER_ID  )
WHERE (SELECT COUNT(*) FROM EMPLOYEES s WHERE s.MANAGER_ID=e.EMPLOYEE_ID GROUP BY e.MANAGER_ID  )>0;
d. UPDATE EMPLOYEES e
SET HIRE_DATE=TRUNC(TO_DATE(HIRE_DATE),'YEAR')
WHERE HIRE_DATE<TO_DATE('01-01-2005','MM-DD-YYYY');
