-- solution 8.3
a. DELETE FROM EMPLOYEES
WHERE SALARY<5000;
b. DELETE FROM LOCATIONS
WHERE LOCATION_ID= ANY(
SELECT LOCATION_ID
FROM LOCATIONS
MINUS
SELECT LOCATION_ID
FROM DEPARTMENTS);
c. DELETE FROM EMPLOYEES
WHERE HIRE_DATE<TO_DATE('01-JAN-1997');
